---
- name: Test DataPower domain module (export)
  connection: local
  hosts: localhost
  vars:
    domain_name: TESTE-ANSIBLE4
    summary: Made with Ansible!!!
    origin: default
  
  tasks:
  
  - name: Include connection data
    include_vars:
        file: connection/idg-connection.yml
        name: remote_idg

  - include: tasks/create.yml  
  - include: tasks/exportDomain.yml       
  - include: tasks/importDomain.yml
