- name: Create domain
  idg_domain:
      name: "{{ domain_name }}"
      idg_connection: "{{ remote_idg }}"
      user_summary: Hecho con Ansible!!!
      state: present
  register: create_domain_out 