---
- name: Test DataPower domain module (export)
  connection: local
  hosts: localhost
  vars:
    domain_name: TESTE-ANSIBLE
    summary: Made with Ansible!!!
    origin: default
  
  tasks:
  
  - name: Include connection data
    include_vars:
        file: idg-connection.yml
        name: remote_idg  

  - name: Export domain
    idg_domain_config:
        name: "{{ origin }}"
        idg_connection: "{{ remote_idg }}"
        state: exported
        all_files: True
        persisted: True
        user_summary: "{{ summary }}"
    register: export_out
#
#  - local_action: copy content={{ export_out }} dest=/tmp/bkp_datapower.zip

#  - name: Dump export output
#    debug:
#        var: export_out['file']

#  - name: Create domain
#    idg_domain:
#        name: "{{ domain_name }}"
#        idg_connection: "{{ remote_idg }}"
#        user_summary: Criado via Ansible!!!
#        state: present
#    register: create_domain_out
#
#  - name: Dump create output
#    debug:
#        var: create_domain_out


  - name: Import domain
    idg_domain_config:
        name: "TESTE-ANSIBLE"
        idg_connection: "{{ remote_idg }}"
        state: imported
        overwrite_files: True
        overwrite_objects: True
        input_file: "{{ export_out['file'] }}"
    register: import_out
#
#  - name: Dump import output
#    debug:
#        var: import_out

#  - name: Update domain
#    idg_domain:
#        name: "{{ domain_name }}"
#        idg_connection: "{{ remote_idg }}"
#        file_map: "{{ file_definition }}"
#        user_summary: "{{ summary }}"
#        state: present
#    vars:
#        file_definition:
#            display: false
#            exec: true
#            copyfrom: false
#            copyto: true
#            delete: false
#            subdir: true    